#!/bin/sh

echo "Running typescript syntax check test."

npx tsc --p .
tscStatus=$?

if [ $tscStatus -ne 0 ]; then
    echo "Typescript typechecking has failed."
    echo "Please fix the errors before merging the commit."
    exit 1
fi

npx next lint
lintStatus=$?

if [ $lintStatus -ne 0 ]; then
    echo "Linting has failed."
    echo "Please fix the errors before merging the commit."
    exit 1
fi

npx prettier . --check
pretStatus=$?

if [ $tscStatus -eq 0 ] && [ $pretStatus -eq 0 ] && [ $lintStatus -eq 0 ]; then
    exit 0
else
    echo "Files do not align with Pretter code convention."
    echo "Please run 'npm run pret:fix' before merging the commit."
    exit 1
fi